---
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.8
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    - repo: https://github.com/jendrikseipp/vulture
      rev: v2.7
      hooks:
          - id: vulture
            args:
                - translator
                - --min-confidence
                - "80"
                - --exclude
                - tests/

    - repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
          - id: black
            language_version: python3

    - repo: https://github.com/DavidAnson/markdownlint-cli2
      rev: v0.10.0
      hooks:
          - id: markdownlint-cli2
            args: ["--config", ".markdownlint-cli2.jsonc"]
            additional_dependencies:
                - markdownlint-cli2@0.10.0

    - repo: https://github.com/rhysd/actionlint
      rev: v1.6.26
      hooks:
          - id: actionlint

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.6
      hooks:
          - id: shellcheck

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            types_or: [toml]
            args: ["--write"]
